sudo: required

services:
  - docker

branches:
  only:
    - master

language: java

jdk: oraclejdk8

cache:
  directories:
  - "$HOME/.cache"

script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn clean deploy"