sudo: required

services:
  - docker

branches:
  only:
    - master

language: java

jdk: oraclejdk8

install: true

cache:
  directories:
  - "$HOME/.cache"

deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn clean package -DskipTests dockerfile:build dockerfile:push"
  skip_cleanup: true
  on:
    tags: true