version: '2'

services:
  rabbitmq:
    image: alvo/twitter-sentiment-analyzer-rabbitmq
    container_name: "rabbitmq_sentiment"
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15674:15674"
    labels:
      NAME: "rabbitmq"
    tty: true

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    hostname: mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USER="user"
      - MONGODB_PASS="mongo"
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles
    tty: true

  sentiment-analyzer:
    image: alvo/twitter-sentiment-analyzer
    hostname: sentiment-analyzer
    container_name: "sentiment_analyzer"
    ports:
      - "8080:8080"
    links:
      - rabbitmq
    labels:
      NAME: "twitter-sentiment-analyzer"
    tty: true

  sentiment-analyzer-dataproxy:
    image: alvo/twitter-sentiment-analyzer-dataproxy
    hostname: twitter-sentiment-analyzer-dataproxy
    container_name: "sentiment_analyzer_dataproxy"
    ports:
      - "8081:8081"
    links:
      - rabbitmq
      - mongodb
    labels:
      NAME: "twitter-sentiment-analyzer-dataproxy"
    tty: true