rabbitmq:
  image: rabbitmq:management
  ports:
    - "5672:5672"
    - "15672:15672"
  labels:
    NAME: "rabbitmq"
  tty: true
  volumes:
    - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    - ./definitions.json:/etc/rabbitmq/definitions.json:ro